import os
import base64
import requests
import json
from dotenv import load_dotenv
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

# Load environment
ENV_PATH = "/workspace/.env"
load_dotenv(ENV_PATH)

WHAPI_TOKEN = os.getenv("WHAPI_TOKEN")
WHATSAPP_GROUP = os.getenv("WHATSAPP_GROUP", "120363426619711887@g.us")

def generate_pdf(md_path, pdf_path):
    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    styles.add(ParagraphStyle(name='AdHeadline', parent=styles['Heading2'], textColor=colors.HexColor("#1877F2"), spaceAfter=6))
    styles.add(ParagraphStyle(name='AdBody', parent=styles['BodyText'], spaceAfter=12, leftIndent=20))
    styles.add(ParagraphStyle(name='CompetitorTitle', parent=styles['Heading1'], spaceBefore=20, spaceAfter=10, textColor=colors.darkblue))
    
    elements = []
    
    # Title
    elements.append(Paragraph("<b>Competitor Ad Intelligence Report (2024-2026)</b>", styles['Title']))
    elements.append(Spacer(1, 0.2*inch))
    elements.append(Paragraph("<i>Generated by Hermes Agent</i>", styles['Normal']))
    elements.append(Spacer(1, 0.5*inch))
    
    with open(md_path, 'r') as f:
        content = f.read()
        
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('## '):
            # Competitor Section
            elements.append(Paragraph(line.replace('## ', ''), styles['CompetitorTitle']))
        elif line.startswith('1. **Headline:**') or line.startswith('**Headline:**') or re.match(r'^[0-9]+\. \*\*Headline:\*\*', line):
            # Ad Headline
            text = line.split('**Headline:**')[-1].strip()
            elements.append(Paragraph(f"<b>Headline:</b> {text}", styles['AdHeadline']))
        elif line.startswith('**Body:**') or line.startswith('   **Body:**'):
            # Ad Body
            text = line.split('**Body:**')[-1].strip()
            elements.append(Paragraph(f"<i>Body:</i> {text}", styles['AdBody']))
        elif line.startswith('**Imagen 2 Prompt:**'):
             # Prompt
             text = line.split('**Imagen 2 Prompt:**')[-1].strip()
             elements.append(Paragraph(f"<b>Creative Prompt:</b> {text}", styles['Italic']))
        elif line.startswith('### '):
             elements.append(Paragraph(line.replace('### ', ''), styles['Heading3']))
        else:
            # Fallback
            elements.append(Paragraph(line, styles['Normal']))
            
    doc.build(elements)
    print(f"PDF generated at {pdf_path}")

def send_whatsapp(file_path):
    with open(file_path, "rb") as f:
        b64_content = base64.b64encode(f.read()).decode('utf-8')
    
    mime_type = "application/pdf"
    file_name = os.path.basename(file_path)
    media_payload = f"data:{mime_type};name={file_name};base64,{b64_content}"

    headers = {
        "accept": "application/json",
        "authorization": f"Bearer {WHAPI_TOKEN}",
        "content-type": "application/json"
    }

    payload = {
        "to": WHATSAPP_GROUP,
        "media": media_payload,
        "caption": "📊 *Competitor Ad Intelligence Report (2024-2026)*\n\nI have extracted 60 non-copyrighted ad copies and creative prompts for your top competitors."
    }

    resp = requests.post("https://gate.whapi.cloud/messages/document", headers=headers, json=payload)
    return resp.status_code, resp.text

import re
if __name__ == "__main__":
    MD_FILE = "/workspace/competitor_ads_report.md"
    PDF_FILE = "/workspace/Competitor_Ad_Report.pdf"
    
    try:
        generate_pdf(MD_FILE, PDF_FILE)
        status, response = send_whatsapp(PDF_FILE)
        print(f"WhatsApp Status: {status}, Response: {response}")
    except Exception as e:
        print(f"Error: {e}")
