import pandas as pd
import datetime

df = pd.read_csv('may4_reflection_final.csv')
date_str = "May 4, 2026"

# Calculate totals
total_spend = df['Spends'].sum()
total_panel_leads = df['Pannel_Lead'].sum()
total_lms_leads = df['LMS Leads'].sum()

# CSS and HTML structure
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Degreefyd Meta Ads Reflection - {date_str}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7f6; color: #333; margin: 0; padding: 20px; }}
        .container {{ max-width: 1200px; margin: auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
        h1 {{ color: #2c3e50; text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }}
        .stat-card {{ background: #ecf0f1; padding: 20px; border-radius: 8px; text-align: center; border-left: 5px solid #3498db; }}
        .stat-card h3 {{ margin: 0; font-size: 14px; text-transform: uppercase; color: #7f8c8d; }}
        .stat-card p {{ margin: 10px 0 0; font-size: 24px; font-weight: bold; color: #2c3e50; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 13px; }}
        th {{ background-color: #3498db; color: white; padding: 12px; text-align: left; position: sticky; top: 0; }}
        td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
        tr:hover {{ background-color: #f1f9ff; }}
        .account-badge {{ padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
        .badge-b {{ background: #d1ecf1; color: #0c5460; }}
        .badge-fyd {{ background: #d4edda; color: #155724; }}
        .badge-ua {{ background: #fff3cd; color: #856404; }}
        .footer {{ margin-top: 30px; text-align: center; font-size: 12px; color: #95a5a6; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Meta Ads Performance Reflection: {date_str}</h1>
        
        <div class="stats-grid">
            <div class="stat-card">
                <h3>Total Spend</h3>
                <p>₹{total_spend:,.2f}</p>
            </div>
            <div class="stat-card">
                <h3>Panel Leads</h3>
                <p>{total_panel_leads}</p>
            </div>
            <div class="stat-card">
                <h3>LMS Verified Leads</h3>
                <p>{total_lms_leads}</p>
            </div>
            <div class="stat-card">
                <h3>Avg. CPL (Panel)</h3>
                <p>₹{total_spend/total_panel_leads if total_panel_leads > 0 else 0:,.2f}</p>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Account</th>
                    <th>Campaign</th>
                    <th>Ad Name</th>
                    <th>Spends (₹)</th>
                    <th>Panel Leads</th>
                    <th>LMS Leads</th>
                </tr>
            </thead>
            <tbody>
"""

for _, row in df.iterrows():
    acc_class = "badge-ua" if "University" in row['Account'] else ("badge-b" if "_B" in row['Account'] else "badge-fyd")
    html_content += f"""
                <tr>
                    <td><span class="account-badge {acc_class}">{row['Account']}</span></td>
                    <td>{row['Campaign']}</td>
                    <td>{row['Ad Name']}</td>
                    <td>₹{row['Spends']:,.2f}</td>
                    <td>{row['Pannel_Lead']}</td>
                    <td>{row['LMS Leads']}</td>
                </tr>
    """

html_content += """
            </tbody>
        </table>
        <div class="footer">Generated by Degreefyd Hermes Intelligence System • Data accurate as of May 4, 2026</div>
    </div>
</body>
</html>
"""

with open('may4_dashboard.html', 'w') as f:
    f.write(html_content)
print("Dashboard HTML generated.")
